### ISSUE TITLE
Pogg

### ISSUE THREAD

**Issue by IcingHackz** [darkdarcool/DarkScript-Compiler#1]
^^^

**Comment by darkdarcool** [comment]
lol this is the first draft of DarkScript, this is just for testing and looking at wut the lang will be like :)

**Comment by darkdarcool** [comment]
also @IcingHackz, please leave suggestions about what to do, so I can make darkscript a good coding lang for the console!

**Comment by IcingHackz** [comment]
so I'm not the best at making programming langs but I can give suggestions...(so just to clarify first um do you literally just make your own commands for the programming lang? Or you have to do specific stuff?)

**Comment by darkdarcool** [comment]
i mean, you can put in commands like bash, but you need some basic things, like printing and stuff. DarkScript it merely a console lang. You can try this code:

``` 
import console.commands.*
window.sp("{blue}{bold}Hello user! What is your name?$n{end}")
string name
window.in(name)
window.sp("{blue}{bold}Hello {name}!!")
```

**Comment by IcingHackz** [comment]
Ok
